version: '3.7'
services:
    database:
        image: 'mysql:5.7'
        command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci"]
        environment:
            MYSQL_DATABASE: btc_db
            MYSQL_USER: btc_user
            MYSQL_PASSWORD: btc_password
            MYSQL_ROOT_PASSWORD: root
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '3306:3306'